[[redirects]]
from = "http://prabhatrana.online/*"
to = "https://prabhatrana.online/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.prabhatrana.online/*"
to = "https://prabhatrana.online/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.prabhatrana.online/*"
to = "https://prabhatrana.online/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200